// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
	translation: {
		analytics: {
			body: "Track active rules, matched keywords, sent DMs, and link clicks so every caption gets smarter.";
			stats: [
				["1,234", "Matched comments"],
				["892", "DMs sent"],
				["38%", "Click-through rate"],
			];
			title: "Know which comments become clicks";
		};
		cta: {
			body: "Create your first auto-DM rule and start sending the right link the moment someone asks.";
			title: "Ready to turn comments into customers?";
		};
		faq: {
			items: [
				[
					"Does this replace my link in bio?",
					"No. It sends the exact link privately when someone asks in comments.",
				],
				[
					"Can I use it before Meta approval?",
					"You can test locally with app roles and tester accounts before public access.",
				],
				[
					"What should captions say?",
					"Use a clear CTA like: Comment outfit and check your inbox.",
				],
			];
			title: "Questions creators ask first";
		};
		footer: {
			dark: "Dark";
			light: "Light";
			system: "System";
			tagline: "Comment-to-DM automation for creator commerce.";
			theme: "Theme";
		};
		hero: {
			body: "Viewers comment a keyword like outfit, hair, or paint — CommentVia sends them an immediate DM with your product link.";
			proofs: [
				"100% automated",
				"Instant DM delivery",
				"More saves, clicks & sales",
			];
			replyAccount: "yourusername";
			replyText: "Check your inbox";
			title: "Turn Instagram comments into instant DM links";
		};
		nav: {
			closeMenu: "Close menu";
			faq: "FAQ";
			getStarted: "Get started";
			how: "How it works";
			language: "Language";
			menu: "Menu";
			pricing: "Pricing";
			signIn: "Sign in";
			useCases: "Use cases";
		};
		pricing: {
			body: "Start with one automation, prove the workflow, then scale to more posts and campaigns.";
			features: [
				"Unlimited keywords",
				"Instagram post and Reel rules",
				"Auto DM preview",
				"Basic analytics",
			];
			period: "/month";
			plan: "Creator";
			price: "$19";
			title: "Simple pricing for the first rule";
		};
		trust: {
			body: "Use tester accounts while building. For a public SaaS, request Meta App Review and Advanced Access for Instagram comment and messaging permissions.";
			items: [
				"Creator or Business account",
				"Connected Facebook Page",
				"Comment webhook events",
				"Private reply / messaging permission",
			];
			title: "Designed around the official Meta path";
		};
		useCases: {
			items: [
				[
					"Fashion drops",
					"Turn outfit, size, and link comments into private product links.",
				],
				[
					"Beauty tutorials",
					"Send product lists when followers ask for hair, brush, or shade.",
				],
				[
					"Digital products",
					"Deliver guides, templates, presets, or lead magnets from one keyword.",
				],
			];
			title: "Built for creators who sell through comments";
		};
		workflow: {
			body: "The best creator tools keep the path short: pick the post, match the comment, send the right link, then watch what converts.";
			steps: [
				[
					"Create a rule",
					"Connect the post or Reel that is already getting attention.",
				],
				[
					"Match intent",
					"Use keywords like outfit, link, recipe, size, price, or paint.",
				],
				[
					"Reply privately",
					"Tell commenters to check their inbox and deliver the shopping link.",
				],
			];
			title: "Launch a comment-to-DM flow in minutes";
		};
	};
}
